name: Terraform Plan and Apply

on:
  workflow_dispatch: # Startar direkt när du klickar på knappen

jobs:
  terraform-deploy:
    name: Terraform Plan and Apply
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    
    permissions:
      contents: read
      id-token: write
   
    concurrency:
      group: gatus-infra
      cancel-in-progress: false

    defaults:
      run:
        shell: bash
        working-directory: Infra

    env:
      TF_IN_AUTOMATION: "true"
      AWS_REGION: eu-central-1
    
    steps:
      - name: Check out validated code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false 

      - name: Install Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: "1.15.6"
          terraform_wrapper: false 

      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: arn:aws:iam::244306245751:role/github-actions-deployment-role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-terraform-deploy

      - name: Initialize Terraform
        run: terraform init -input=false 

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -lock-timeout=5m -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false -no-color -lock-timeout=5m tfplan
